#!/usr/bin/env bash
#
# Copyright 2026 The OKDP Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#

# Renders the Flux-only files of the deployments repository from the engine-neutral
# instance.yaml files. The output format is a contract (see gitops/README.md,
# "Generated files"): the control plane server's Go writer produces the same bytes.
#
#   projects/<p>/services/<i>/helmrelease.yaml    OCIRepository + HelmRelease
#   projects/<p>/services/<i>/kustomization.yaml  values ConfigMap generator
#   projects/<p>/kustomization.yaml               services + connection ConfigMaps
#   platform/components/<NN>-<i>/helmrelease.yaml, kustomization.yaml
#   platform/kustomization.yaml                   platform values + platform connection ConfigMaps
#   flux/components.yaml                          one Flux Kustomization per component + okdp-projects
#
# Usage: render-flux.sh [--root DIR] [--path-prefix PREFIX]
#   --root         the layout root (default: the parent of this script's directory)
#   --path-prefix  path of the layout root inside its Git repository, used only in
#                  flux/components.yaml (default: computed with git, "" at the repo root)
#
# Requires bash >= 4 and yq v4 (mikefarah).

set -euo pipefail
export LC_ALL=C

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PREFIX=""
PREFIX_SET=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --root) ROOT="$(cd "$2" && pwd)"; shift 2 ;;
    --path-prefix) PREFIX="$2"; PREFIX_SET=true; shift 2 ;;
    -h|--help) sed -n '18,36p' "$0"; exit 0 ;;
    *) echo "render-flux: unknown argument: $1" >&2; exit 2 ;;
  esac
done

if ! $PREFIX_SET; then
  PREFIX="$(git -C "$ROOT" rev-parse --show-prefix 2>/dev/null || true)"
fi
PREFIX="${PREFIX%/}"

command -v yq >/dev/null || { echo "render-flux: yq v4 is required" >&2; exit 2; }
yq --version 2>&1 | grep -q 'version v4' || { echo "render-flux: yq v4 (mikefarah) is required" >&2; exit 2; }

HEADER="# Generated by scripts/render-flux.sh. Do not edit."
DNS_RE='^[a-z0-9]([-a-z0-9]*[a-z0-9])?$'
CHART_RE='^oci://[a-z0-9]([-a-z0-9.]*[a-z0-9])?(:[0-9]+)?(/[a-z0-9]([-a-z0-9._]*[a-z0-9])?)+$'
VERSION_RE='^[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z][-0-9A-Za-z.]*)?$'
LAYERS=(00 10 20 30)

errors=0
err() { echo "render-flux: $*" >&2; errors=$((errors + 1)); }

declare -A RELEASES=()      # release name -> instance.yaml, for uniqueness
declare -A CONFIGMAPS=()    # okdp-releases ConfigMap name -> source, for uniqueness

claim_release() {
  local rel="$1" src="$2"
  if [[ -n "${RELEASES[$rel]:-}" ]]; then
    err "$src: release name $rel already used by ${RELEASES[$rel]}"
  fi
  RELEASES[$rel]="$src"
}

claim_configmap() {
  local cm="$1" src="$2"
  if [[ -n "${CONFIGMAPS[$cm]:-}" ]]; then
    err "$src: ConfigMap okdp-releases/$cm already produced by ${CONFIGMAPS[$cm]}"
  fi
  CONFIGMAPS[$cm]="$src"
}

# Nothing is written until every input is valid: outputs are staged first.
STAGE="$(mktemp -d)"
trap 'rm -rf "$STAGE"' EXIT
REMOVALS=()

# write FILE: stage stdin as the new content of FILE.
write() {
  local rel="${1#"$ROOT"/}"
  mkdir -p "$STAGE/$(dirname "$rel")"
  cat >"$STAGE/$rel"
}

# remove_generated FILE: schedule the removal of FILE if it is a generated file
# (an orphan left by a deleted instance.yaml).
remove_generated() {
  if [[ -f "$1" ]] && [[ "$(head -n 1 "$1")" == "$HEADER" ]]; then
    REMOVALS+=("$1")
  fi
}

# apply: move the staged files into place (only when the bytes differ, which keeps
# mtimes stable) and perform the scheduled removals.
apply() {
  local staged rel file
  while IFS= read -r staged; do
    rel="${staged#"$STAGE"/}"
    file="$ROOT/$rel"
    if [[ -f "$file" ]] && cmp -s "$staged" "$file"; then continue; fi
    mkdir -p "$(dirname "$file")"
    cp "$staged" "$file"
    chmod 0644 "$file"
    echo "rendered $rel"
  done < <(find "$STAGE" -type f | sort)
  for file in "${REMOVALS[@]}"; do
    rm -f "$file"
    echo "removed ${file#"$ROOT"/}"
  done
}

# Reads and validates an instance.yaml. Sets I_NAME I_PROJECT I_SERVICE I_CHART
# I_VERSION I_CONNECTIONS (array). Returns 1 when invalid.
read_instance() {
  local file="$1" rel="${1#"$ROOT"/}" before=$errors key type
  if ! yq -e 'tag == "!!map"' "$file" >/dev/null 2>&1; then
    err "$rel: not a YAML mapping"; return 1
  fi
  local keys
  keys="$(yq '[keys[]] | sort | join(",")' "$file")"
  if [[ "$keys" != "chart,connections,name,project,service,version" ]]; then
    err "$rel: keys must be exactly name, project, service, chart, version, connections (found: $keys)"
    return 1
  fi
  for key in name project service chart version; do
    type="$(yq ".$key | tag" "$file")"
    [[ "$type" == "!!str" ]] || err "$rel: $key must be a string (found $type; quote it)"
  done
  [[ "$(yq '.connections | tag' "$file")" == "!!seq" ]] || err "$rel: connections must be a list"
  [[ "$(yq '[.connections[] | select(tag != "!!str")] | length' "$file")" == "0" ]] \
    || err "$rel: connections must be a list of strings"
  (( errors == before )) || return 1

  I_NAME="$(yq '.name' "$file")"
  I_PROJECT="$(yq '.project' "$file")"
  I_SERVICE="$(yq '.service' "$file")"
  I_CHART="$(yq '.chart' "$file")"
  I_VERSION="$(yq '.version' "$file")"
  mapfile -t I_CONNECTIONS < <(yq '.connections[]' "$file")

  [[ "$I_NAME" =~ $DNS_RE ]] || err "$rel: name '$I_NAME' is not a DNS label"
  [[ "$I_PROJECT" =~ $DNS_RE ]] || err "$rel: project '$I_PROJECT' is not a DNS label"
  [[ "$I_SERVICE" =~ $DNS_RE ]] || err "$rel: service '$I_SERVICE' is not a DNS label"
  [[ "$I_CHART" =~ $CHART_RE ]] || err "$rel: chart '$I_CHART' is not an oci:// chart reference"
  [[ "${I_CHART##*/}" == "$I_SERVICE" ]] || err "$rel: chart '$I_CHART' must end with /$I_SERVICE"
  [[ "$I_VERSION" =~ $VERSION_RE ]] || err "$rel: version '$I_VERSION' is not an exact semantic version"
  local rlen=$(( ${#I_PROJECT} + 1 + ${#I_NAME} ))
  (( rlen <= 53 )) || err "$rel: release name $I_PROJECT-$I_NAME is longer than 53 characters"
  local c seen=" "
  for c in "${I_CONNECTIONS[@]}"; do
    [[ "$c" =~ $DNS_RE ]] || err "$rel: connection '$c' is not a DNS label"
    [[ "$seen" != *" $c "* ]] || err "$rel: connection '$c' listed twice"
    seen+="$c "
  done
  (( errors == before ))
}

# emit_helmrelease PROJECT NAME CHART VERSION CONN_PREFIX CONNECTION...
# CONN_PREFIX: "conn-<p>-" for a service, "okdp-platform-conn-" for a component.
emit_helmrelease() {
  local p="$1" i="$2" chart="$3" version="$4" cprefix="$5"; shift 5
  local r="$p-$i" c note=""
  # TODO(no-kubocd): temporary registry, revert to quay.io/okdp once the OKDP charts are published there.
  [[ "$chart" == oci://repo.alliage.io* ]] && note=$'  # TODO(no-kubocd): temporary registry, revert to quay.io/okdp once the OKDP charts are published there.\n'
  cat <<EOF
$HEADER
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: "$r"
  namespace: okdp-releases
  labels:
    okdp.io/project: "$p"
    okdp.io/instance: "$r"
spec:
  interval: 10m
${note}  url: "$chart"
  ref:
    tag: "$version"
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: "$r"
  namespace: okdp-releases
  labels:
    okdp.io/project: "$p"
    okdp.io/instance: "$r"
spec:
  interval: 10m
  releaseName: "$r"
  targetNamespace: "$p"
  storageNamespace: "$p"
  chartRef:
    kind: OCIRepository
    name: "$r"
  timeout: 15m
  install:
    createNamespace: true
    strategy:
      name: RetryOnFailure
      retryInterval: 2m
  upgrade:
    remediation:
      retries: 3
      strategy: rollback
  driftDetection:
    mode: enabled
  valuesFrom:
    - kind: ConfigMap
      name: okdp-platform-values
      valuesKey: values.yaml
EOF
  for c in "$@"; do
    cat <<EOF
    - kind: ConfigMap
      name: "$cprefix$c"
      valuesKey: values.yaml
EOF
  done
  cat <<EOF
    - kind: ConfigMap
      name: "values-$r"
      valuesKey: values.yaml
EOF
}

# emit_instance_kustomization PROJECT NAME
emit_instance_kustomization() {
  cat <<EOF
$HEADER
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: okdp-releases
resources:
  - helmrelease.yaml
configMapGenerator:
  - name: "values-$1-$2"
    files:
      - values.yaml
    options:
      disableNameSuffixHash: true
      labels:
        reconcile.fluxcd.io/watch: Enabled
EOF
}

# emit_project_kustomization PROJECT SERVICES_NEWLINE_LIST CONNECTIONS_NEWLINE_LIST
emit_project_kustomization() {
  local p="$1" services="$2" connections="$3" s c
  echo "$HEADER"
  echo "apiVersion: kustomize.config.k8s.io/v1beta1"
  echo "kind: Kustomization"
  echo "namespace: okdp-releases"
  if [[ -z "$services" ]]; then
    echo "resources: []"
  else
    echo "resources:"
    while IFS= read -r s; do echo "  - services/$s"; done <<<"$services"
  fi
  if [[ -z "$connections" ]]; then
    echo "configMapGenerator: []"
  else
    echo "configMapGenerator:"
    while IFS= read -r c; do
      cat <<EOF
  - name: "conn-$p-$c"
    files:
      - values.yaml=connections/$c.yaml
    options:
      disableNameSuffixHash: true
      labels:
        reconcile.fluxcd.io/watch: Enabled
EOF
    done <<<"$connections"
  fi
}

# emit_platform_kustomization CONNECTIONS_NEWLINE_LIST
emit_platform_kustomization() {
  local connections="$1" c
  cat <<EOF
$HEADER
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: okdp-releases
configMapGenerator:
  - name: okdp-platform-values
    files:
      - values.yaml=platform-values.yaml
    options:
      disableNameSuffixHash: true
      labels:
        reconcile.fluxcd.io/watch: Enabled
EOF
  [[ -n "$connections" ]] || return 0
  while IFS= read -r c; do
    cat <<EOF
  - name: "okdp-platform-conn-$c"
    files:
      - values.yaml=connections/$c.yaml
    options:
      disableNameSuffixHash: true
      labels:
        reconcile.fluxcd.io/watch: Enabled
EOF
  done <<<"$connections"
}

# Lists the names of the sub-directories of DIR, sorted (byte order).
subdirs() {
  local d
  [[ -d "$1" ]] || return 0
  for d in "$1"/*/; do
    [[ -d "$d" ]] || continue
    d="${d%/}"
    echo "${d##*/}"
  done | sort
}

# ---------------------------------------------------------------- projects
for p in $(subdirs "$ROOT/projects"); do
  pdir="$ROOT/projects/$p"
  if [[ ! "$p" =~ $DNS_RE ]]; then err "projects/$p: directory name is not a DNS label"; continue; fi
  if [[ ! -f "$pdir/project.yaml" ]]; then err "projects/$p: missing project.yaml"; continue; fi
  pname="$(yq '.name' "$pdir/project.yaml" 2>/dev/null || true)"
  [[ "$pname" == "$p" ]] || err "projects/$p/project.yaml: name must be '$p' (found '$pname')"

  connections=""
  if [[ -d "$pdir/connections" ]]; then
    for f in "$pdir"/connections/*; do
      [[ -e "$f" ]] || continue
      c="${f##*/}"
      if [[ "$c" != *.yaml ]]; then err "projects/$p/connections/$c: connection files end with .yaml"; continue; fi
      c="${c%.yaml}"
      [[ "$c" =~ $DNS_RE ]] || { err "projects/$p/connections/$c.yaml: name is not a DNS label"; continue; }
      claim_configmap "conn-$p-$c" "projects/$p/connections/$c.yaml"
      connections+="$c"$'\n'
    done
  fi
  connections="$(sort <<<"${connections%$'\n'}")"

  services=""
  for i in $(subdirs "$pdir/services"); do
    idir="$pdir/services/$i"
    if [[ ! -f "$idir/instance.yaml" ]]; then
      remove_generated "$idir/helmrelease.yaml"
      remove_generated "$idir/kustomization.yaml"
      continue
    fi
    read_instance "$idir/instance.yaml" || continue
    rel="projects/$p/services/$i/instance.yaml"
    [[ "$I_NAME" == "$i" ]] || { err "$rel: name must be '$i' (the directory name)"; continue; }
    [[ "$I_PROJECT" == "$p" ]] || { err "$rel: project must be '$p' (the project directory)"; continue; }
    [[ -f "$idir/values.yaml" ]] || { err "projects/$p/services/$i: missing values.yaml (use {} when empty)"; continue; }
    ok=true
    for c in "${I_CONNECTIONS[@]}"; do
      [[ -f "$pdir/connections/$c.yaml" ]] || { err "$rel: connection file projects/$p/connections/$c.yaml does not exist"; ok=false; }
    done
    $ok || continue
    claim_release "$p-$i" "$rel"
    claim_configmap "values-$p-$i" "$rel"
    emit_helmrelease "$p" "$i" "$I_CHART" "$I_VERSION" "conn-$p-" "${I_CONNECTIONS[@]}" | write "$idir/helmrelease.yaml"
    emit_instance_kustomization "$p" "$i" | write "$idir/kustomization.yaml"
    services+="$i"$'\n'
  done
  services="${services%$'\n'}"

  emit_project_kustomization "$p" "$services" "$connections" | write "$pdir/kustomization.yaml"
done

# ---------------------------------------------------- platform connections
pconnections=""
if [[ -d "$ROOT/platform/connections" ]]; then
  for f in "$ROOT"/platform/connections/*; do
    [[ -e "$f" ]] || continue
    c="${f##*/}"
    if [[ "$c" != *.yaml ]]; then err "platform/connections/$c: connection files end with .yaml"; continue; fi
    c="${c%.yaml}"
    [[ "$c" =~ $DNS_RE ]] || { err "platform/connections/$c.yaml: name is not a DNS label"; continue; }
    claim_configmap "okdp-platform-conn-$c" "platform/connections/$c.yaml"
    pconnections+="$c"$'\n'
  done
fi
pconnections="$(sort <<<"${pconnections%$'\n'}")"
emit_platform_kustomization "$pconnections" | write "$ROOT/platform/kustomization.yaml"

# ------------------------------------------------------ platform components
declare -A LAYER_COMPONENTS=()
for d in $(subdirs "$ROOT/platform/components"); do
  cdir="$ROOT/platform/components/$d"
  if [[ ! -f "$cdir/instance.yaml" ]]; then
    remove_generated "$cdir/helmrelease.yaml"
    remove_generated "$cdir/kustomization.yaml"
    continue
  fi
  if [[ ! "$d" =~ ^([0-9][0-9])-(.+)$ ]]; then err "platform/components/$d: directory must be named <NN>-<name>"; continue; fi
  layer="${BASH_REMATCH[1]}"; cname="${BASH_REMATCH[2]}"
  if [[ " ${LAYERS[*]} " != *" $layer "* ]]; then err "platform/components/$d: layer $layer is not one of ${LAYERS[*]}"; continue; fi
  read_instance "$cdir/instance.yaml" || continue
  rel="platform/components/$d/instance.yaml"
  [[ "$I_NAME" == "$cname" ]] || { err "$rel: name must be '$cname' (the directory name without the layer)"; continue; }
  [[ -f "$cdir/values.yaml" ]] || { err "platform/components/$d: missing values.yaml (use {} when empty)"; continue; }
  ok=true
  for c in "${I_CONNECTIONS[@]}"; do
    [[ -f "$ROOT/platform/connections/$c.yaml" ]] || { err "$rel: connection file platform/connections/$c.yaml does not exist"; ok=false; }
  done
  $ok || continue
  claim_release "$I_PROJECT-$I_NAME" "$rel"
  claim_configmap "values-$I_PROJECT-$I_NAME" "$rel"
  emit_helmrelease "$I_PROJECT" "$I_NAME" "$I_CHART" "$I_VERSION" "okdp-platform-conn-" "${I_CONNECTIONS[@]}" | write "$cdir/helmrelease.yaml"
  emit_instance_kustomization "$I_PROJECT" "$I_NAME" | write "$cdir/kustomization.yaml"
  LAYER_COMPONENTS[$layer]+="$d "
done

if (( errors > 0 )); then
  echo "render-flux: $errors error(s); nothing written" >&2
  exit 1
fi

# flux/components.yaml: one Flux Kustomization per component; each component
# depends on every component of the nearest lower non-empty layer, the lowest
# layer on okdp-platform-values.
if [[ -n "$PREFIX" ]]; then base="./$PREFIX/platform/components"; else base="./platform/components"; fi
{
  echo "# Generated by scripts/render-flux.sh. Do not edit."
  previous="okdp-platform-values"
  for layer in "${LAYERS[@]}"; do
    [[ -n "${LAYER_COMPONENTS[$layer]:-}" ]] || continue
    for d in ${LAYER_COMPONENTS[$layer]}; do
      cat <<EOF
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: okdp-component-$d
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  timeout: 10m
  sourceRef:
    kind: GitRepository
    name: okdp-gitops
  path: $base/$d
  prune: true
  wait: true
  dependsOn:
EOF
      for dep in $previous; do echo "    - name: $dep"; done
    done
    previous=""
    for d in ${LAYER_COMPONENTS[$layer]}; do previous+="okdp-component-$d "; done
  done
  # The project services start once the platform is ready (a service installed
  # before the ingress webhook or the CA bundle exists exhausts its install retries).
  cat <<EOF
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: okdp-projects
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: okdp-gitops
  path: ${base%/platform/components}/projects
  prune: true
  dependsOn:
EOF
  for dep in $previous; do echo "    - name: $dep"; done
} | write "$ROOT/flux/components.yaml"

apply
